### ISSUE TITLE
Compiling the Marvin example gives warnings

### ISSUE THREAD

**Issue by hjnijlunsing** [kpn-iot/thingsml-c-library#12] opened 2021-03-29 16:49 UTC
When compiling the standard Marvin example I receive the following warnings:

C:\Users\user\Documents\Arduino\libraries\ThingsML\src\thingsml_http_firmware.cpp: In static member function 'static uint32_t ThingsML::HttpFirmwareDownload::calculateCRC32FromBody(char*, int)':
C:\Users\user\Documents\Arduino\libraries\ThingsML\src\thingsml_http_firmware.cpp:295:42: warning: left shift count >= width of type [-Wshift-count-overflow]
             uint32_t a   = (low * ((1 << 23) + (1 << 14) + (1 << 2)));
                                          ^~
C:\Users\user\Documents\Arduino\libraries\ThingsML\src\thingsml_http_firmware.cpp:297:31: warning: left shift count >= width of type [-Wshift-count-overflow]
                 (low * ((1 << 24) + (1 << 16) + (1 << 8))) ^
                               ^~
C:\Users\user\Documents\Arduino\libraries\ThingsML\src\thingsml_http_firmware.cpp:297:43: warning: left shift count >= width of type [-Wshift-count-overflow]
                 (low * ((1 << 24) + (1 << 16) + (1 << 8))) ^
                                           ^~
C:\Users\user\Documents\Arduino\libraries\ThingsML\src\thingsml_http_firmware.cpp:300:31: warning: left shift count >= width of type [-Wshift-count-overflow]
                 (low * ((1 << 20) + (1 << 12)           )) ^
                               ^~
C:\Users\user\Documents\Arduino\libraries\ThingsML\src\cbor\cbor.cpp: In function 'uint16_t half_float_to_binary(float)':
C:\Users\user\Documents\Arduino\libraries\ThingsML\src\cbor\cbor.cpp:125:21: warning: result of '(112 << 10)' requires 18 bits to represent, but 'int' only has 16 bits [-Wshift-overflow=]
         t3 -= (112) << 10;  // Adjust for bias difference (-127 + 15)
               ~~~~~~^~~~~

**Comment by josephverburg** [comment] 2021-09-07 15:26
How are you producing these compile errors, i cannot seem to be able to reproduce them. 
Which version of the Arduino IDE are you using?
Are you using any other libraries?
Which operating system are you compiling on ?

**Comment by robinbode** [comment] 2024-05-22 09:29
Since we haven't received any further response or feedback, we are closing this issue. If you have any additional information or need further assistance, please feel free to reopen it or create a new issue. Thank you!

**Closed** 2024-05-22 09:30 UTC
